import tkinter as tk
root = tk.Tk()
root.title("Калькуляторочив")
root.geometry("800x500")
label = tk.Label(root, text="Калькулятор", font=("Arial", 18))
label.pack(padx=20, pady=20)
textbox = tk.Text(root, height=3, font=("Arial", 16))
textbox.pack(padx=20, pady=20)
buttonFrame = tk.Frame(root)
buttonFrame.pack(fill="x")
buttonFrame.columnconfigure(0, weight=1)
buttonFrame.columnconfigure(1, weight=1)
buttonFrame.columnconfigure(2, weight=1)
buttonFrame.columnconfigure(3, weight=1)
btn1 = tk.Button(buttonFrame, text="1", font=("Arial", 18))
btn2 = tk.Button(buttonFrame, text="2", font=("Arial", 18))
btn3 = tk.Button(buttonFrame, text="3", font=("Arial", 18))
btn4 = tk.Button(buttonFrame, text="-", font=("Arial", 18))
btn5 = tk.Button(buttonFrame, text="4", font=("Arial", 18))
btn6 = tk.Button(buttonFrame, text="5", font=("Arial", 18))
btn7 = tk.Button(buttonFrame, text="6", font=("Arial", 18))
btn8 = tk.Button(buttonFrame, text="+", font=("Arial", 18))
btn9 = tk.Button(buttonFrame, text="7", font=("Arial", 18))
btn10 = tk.Button(buttonFrame, text="8", font=("Arial", 18))
btn11 = tk.Button(buttonFrame, text="9", font=("Arial", 18))
btn12 = tk.Button(buttonFrame, text="+", font=("Arial", 18))


btn1.grid(row=0, column=0, sticky="we")
btn2.grid(row=0, column=1, sticky="we")
btn3.grid(row=0, column=2, sticky="we")
btn4.grid(row=0, column=3, sticky="we")
btn5.grid(row=1, column=0, sticky="we")
btn6.grid(row=1, column=1, sticky="we")
btn7.grid(row=1, column=2, sticky="we")
btn8.grid(row=1, column=3, sticky="we")
btn9.grid(row=2, column=0, sticky="we")
btn10.grid(row=2, column=1, sticky="we")
btn11.grid(row=2, column=2, sticky="we")
btn12.grid(row=2, column=3, sticky="we")

root.mainloop()
print("Я ЛОХ")
